name: CI

on:
  push:
    branches:
      - develop

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.0.3
        with:
          go-version: 1.13
      - uses: actions/checkout@v2
      - name: Install Linux packages
        run: sudo apt update && sudo apt install -y --no-install-recommends libopenal1 libopenal-dev libasound2-dev libx11-dev libx11-xcb-dev
      - name: Build
        run: make bin
  windows:
    runs-on: windows-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.0.3
        with:
          go-version: 1.13
      - uses: actions/checkout@v2
      - name: Build
        run: make bin
  macos:
    runs-on: macos-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.0.3
        with:
          go-version: 1.13
      - uses: actions/checkout@v2
      - name: Build
        run: make bin
